@echo off
REM Parando API do Compilador...
FOR /F "tokens=*" %%i IN ('docker ps -q -f "ancestor=sprint3_api_compiler"') DO docker stop %%i
REM Parando API de Arquivos...
FOR /F "tokens=*" %%i IN ('docker ps -q -f "ancestor=sprint3_api_files"') DO docker stop %%i
REM Parando API de Usuarios...
FOR /F "tokens=*" %%i IN ('docker ps -q -f "ancestor=sprint3_api_users"') DO docker stop %%i
REM Parando o back do Front...
FOR /F "tokens=*" %%i IN ('docker ps -q -f "ancestor=sprint3_front"') DO docker stop %%i
